balaji/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('shreebalaji.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shreebalaji/urls.py
from django.urls import path
from .views import *

app_name = 'shreebalaji'

urlpatterns = [
    path('', index, name='index'),
    path('galleries/', galleries, name='gallaries'),
    path('services', Services.as_view(), name='services'),
    path('aboutus', AboutUs.as_view(), name='aboutus'),
    path('contactus', ContactUs.as_view(), name='contactus'),
    path('ongoing', Ongoing.as_view(), name='ongoing'),
    path('completed', Completed.as_view(), name='completed'),
]

cms/models.py
from django.db import models


# Create your models here.
class Banner(models.Model):
    caption = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='Banners')

    def __str__(self):
        return self.caption

shreebalaji/models.py
from django.db import models
import datetime
from ckeditor.fields import RichTextField


# Create your models here.

class Gallery(models.Model):
    image = models.ImageField(upload_to='galleries')
    caption = models.CharField(max_length=50)
    publish_date = models.DateTimeField(datetime.datetime.now())

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name_plural = "Galleries"


class ProjectStatus(models.Model):
    status = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'ProjectStatus'

    def __str__(self):
        return self.status


class Project(models.Model):
    title = models.CharField(max_length=100)
    status = models.ForeignKey(ProjectStatus, on_delete=models.CASCADE)
    descriptions = RichTextField()

    def __str__(self):
        return self.title


class ContactUs(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = 'ContactUs'

cms/views.py
from django.shortcuts import render

# Create your views here.

shreebalaji/views.py
from django.contrib import messages
from django.shortcuts import render
from django.views import View
from cms.models import Banner
from .models import Gallery, Project
from .form import ContactUsForm
from django.shortcuts import get_object_or_404


# Create your views here.
class Index(View):
    template_name = 'index.html'

    def get(self, request):
        return render(request, self.template_name)


def index(request):
    banners = Banner.objects.all()
    context = {
        'banners': banners
    }
    return render(request, 'index.html', context)


def galleries(request):
    images = Gallery.objects.order_by('-publish_date')
    context = {
        'images': images
    }
    return render(request, 'galleries.html', context)


class Services(View):
    template_name = 'services.html'

    def get(self, request):
        return render(request, self.template_name)


class ContactUs(View):
    template_name = 'contactus.html'

    def get(self, request):
        form = ContactUsForm()
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message has been recorded Successfully.')
        else:
            messages.error(request, 'Error in submitting the message. Try Again... ')
        return render(request, self.template_name, {'form': form})


class AboutUs(View):
    template_name = 'aboutus.html'

    def get(self, request):
        return render(request, self.template_name)


class Ongoing(View):
    template_name = 'ongoingproject.html'

    def get(self, request):
        project = Project.objects.filter(status__status__icontains='ongoing')
        return render(request, self.template_name, {'project': project})


class Completed(View):
    template_name = 'completedproject.html'

    def get(self, request):
        project = Project.objects.filter(status__status__icontains='completed')
        return render(request, self.template_name, {'project': project})

shreebalaji/templates/aboutus.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <style>
        .jumbotron {
            padding-top: 10px;
            padding-bottom: 10px;
            background-color: gray;
        }
    </style>
    <div class="jumbotron">
        <h1 class="display-4" align="center"><b>About Us</b></h1>
    </div>
    <div>
        <h3 style="padding-bottom: 10px">Message from Managing Director(M.D)</h3>
        <div style="padding-bottom: 10px">
            <img src="{% static 'images/MD.jpg' %}" align="left" height="150px" width="150px"
                 style="padding-right: 10px">
            <p align="justify">
                Nepal has a high potential of hydropower energy which can overcome the
                problem of energy crisis prevailing in the country and can be energy center
                for Asia.<br/><br/>
                With the government strategy of emphasizing on the full optimization of the hydro energy these days, the
                number of workshop to manufacture and repair the HM parts has been limited .
                To fulfill required need ShreeBalaji Hydro & Engineering Pvt.Ltd. was established focusing on hydropower
                projects, fabrication of parts, erection, repair & maintenance.<br/><br/>
                We have a combination of skilled manpower, modern tools and equipments, highly sophisticated machinery
                and a
                strong financial background. Hence, dealing with the hydropower projects is not cumbersome for us.
                Shreebalaji has successfully completed projects having head ranging from (65-765 mtr.) and is planning
                to
                move on for larger projects. We are specialized in designing, manufacturing, erection and repair of
                hydro-mechanical components and other similar structural works.We are more of a service oriented rather
                than
                profit oriented and I believe Shree Balaji will fulfill your desire with full satisfaction.
            </p>
        </div>
    </div>
    <div>
        <h3 style="padding-bottom: 10px">Mission Statement</h3>
        <p align="justify">
            “Our mission is to develop complete solution for design, fabrication and erection of steel structure
            focusing development of hydropower .’’
        </p>
    </div>
    <div>
        <h3 style="padding-bottom: 10px">Vision Statement</h3>
        <p align="justify">
            Our vision is to be the best hydropower consulting and developing company in Nepal which commits work
            assurance meeting international standard . By 2025 , We will be the strongest market competitive in Civil,
            Hydro-mechanical & Electro-mechanical works.
        </p>
    </div>
    <div>
        <h3 style="padding-bottom: 10px">About Company</h3>
        <p align="justify">
            <b>ShreeBalaji Hydro and Engineering Pvt. Ltd</b> was established in the year 2075 under Companies Act 2006 with
            <b>registration number 189101/74/075 and VAT number 606714822</b>. Established under Private Firm Registered Act
            2014, our company was first registered with the name Shree Balaji Engineering works which was a proprietor
            company with its registration number 40983/1683 and VAT number as 601057621.<br/><br/> The head office of the company
            is located at <b>New Baneshwor, Kathmandu, Nepal</b> . In short this works in the field of Erection of Hydro
            mechanical and Structural Engineering Services since 2013. Our key motive is creating an outstanding
            experience for each and every one of our clients.<br/><br/>

            We provide excellent commitment in field of <b>planning, design, fabrication, installation, quality management
            and testing & commissioning</b>. Our experienced, knowledgeable team can perform detail engineering, fabrication
            and installation of all the hydro-mechanical items and structures such as Headrace and Penstock pipes, Bell
            mouths, Gates and Stop logs, Hoisting, Bends, Trash racks, Bifurcations, Flushing Pipes, Draft Tubes,
            Expansion Joints, etc. We ensure you timely project completion, end-to-end quality management and budget
            control.

        </p>
    </div>
{% endblock %}

shreebalaji/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>

<body style="margin: 15px;">
<header>
    <div class="top-header">
        <table align="center" style="width: 100%">
            <tr>
                <td>
                    <div class=" float-right">
                        <i class="fas fa-phone mr-3" title="phone"></i> +977 14483582 |
                        <i class="fas fa-envelope mr-3" title="email"></i> tmbalasingh@gmail.com |
                        <i class="fas fa-home mr-3" title="address"></i> Head office- New Baneswor, Kathmandu, Nepal
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="header">
        <table align="center" style="width: 100%">
            <tr>
                <td><img src="{% static 'images/logo.png' %}" height="100" width="120"></td>
                <td>
                    <h1>ShreeBalaji Hydro and Engineering Pvt.Ltd</h1>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
        </table>
        <table align="center" style="width: 100%">
            <tr>

                <td>
                    <marquee style="color: red;">A complete solution for design, fabrication and erection of steel
                        structure.
                    </marquee>
                </td>

            </tr>
        </table>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'shreebalaji:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shreebalaji:services' %}">Services</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shreebalaji:gallaries' %}">Galleries</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shreebalaji:aboutus' %}">About Us</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Projects
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'shreebalaji:ongoing' %}">On-going Projects</a>
                        <a class="dropdown-item" href="{% url 'shreebalaji:completed' %}">Completed Projects</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shreebalaji:contactus' %}">Contact Us</a>
                </li>
            </ul>
        </div>
    </nav>

</header>
<div style="padding-bottom: 10px"></div>
<main>
    {% block content %}{% endblock %}
</main>
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4">

    <div style="background-color: #6351ce;">
        <div class="container">

            <!-- Grid row-->
            <div class="row py-4 d-flex align-items-center">

                <!-- Grid column -->
                <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
                    <h6 class="mb-0">Get connected with us on social networks!</h6>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-6 col-lg-7 text-center text-md-right">

                    <!-- Facebook -->
                    <a class="fb-ic">
                        <i class="fab fa-facebook-f white-text mr-4"> </i>
                    </a>
                    <!-- Twitter -->
                    <a class="tw-ic">
                        <i class="fab fa-twitter white-text mr-4"> </i>
                    </a>
                    <!-- Google +-->
                    <a class="gplus-ic">
                        <i class="fab fa-google-plus-g white-text mr-4"> </i>
                    </a>
                    <!--Linkedin -->
                    <a class="li-ic">
                        <i class="fab fa-linkedin-in white-text mr-4"> </i>
                    </a>
                    <!--Instagram-->
                    <a class="ins-ic">
                        <i class="fab fa-instagram white-text"> </i>
                    </a>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row-->

        </div>
    </div>

    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">

        <!-- Grid row -->
        <div class="row mt-3">

            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

                <!-- Content -->
                <h6 class="text-uppercase font-weight-bold">ShreeBalaji Hydro and Engineering Pvt.Ltd</h6>
                <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                <div style="padding: 10px;">
                    <img src="{% static 'images/logo.png' %}" height="100" width="120">
                </div>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

                <!-- Links -->
                <h6 class="text-uppercase font-weight-bold">Services</h6>
                <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                <p>
                    Penstock pipe & Head race pipe
                </p>
                <p>
                    Gates with its accessories
                </p>
                <p>Stop log with its accessories</p>
                <p>Communication Towers</p>
                <p>
                    <a href="{% url 'shreebalaji:services' %}">more...</a>
                </p>


            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

                <!-- Links -->
                <h6 class="text-uppercase font-weight-bold">Useful links</h6>
                <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                <p>
                    <a href="{% url 'shreebalaji:aboutus' %}">About Us</a>
                </p>
                <p>
                    <a href="{% url 'shreebalaji:gallaries' %}">Galleries</a>
                </p>
                <p>
                    <a href="{% url 'shreebalaji:contactus' %}">Contact Us</a>
                </p>
                  <p>
                    <a href="{% url 'shreebalaji:ongoing' %}">OnGoing Projects</a>
                </p>
                  <p>
                    <a href="{% url 'shreebalaji:completed' %}">Completed Projects</a>
                </p>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

                <!-- Links -->
                <h6 class="text-uppercase font-weight-bold">Contact</h6>
                <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                <p>
                    <i class="fas fa-home mr-3"></i> Head office- New Baneswor, Kathmandu, Nepal</p>
                <p>
                    <i class="fas fa-envelope mr-3"></i> tmbalasingh@gmail.com</p>
                <p>
                    <i class="fas fa-envelope mr-3"></i> shree.bhe@gmail.com</p>
                </p>
                <p>
                    <i class="fas fa-phone mr-3"></i> +977 14483582
                <p>
                <div>
                 <img src="{% static 'images/map.png' %}" height="200" width="250">
            </div>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <P>ShreeBalaji Hydro and Engineering Pvt.Ltd</p>
        <p>Featured contents are <a href="https://bootsnipp.com/license">MIT license.</a> </p>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

shreebalaji/templates/completedproject.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .jumbotron {
            padding-top: 10px;
            padding-bottom: 10px;
            background-color: gray;
        }
    </style>
    <div class="jumbotron">
        <h1 class="display-4" align="center"><b>Completed Projects</b></h1>
    </div>
    <div class="row">
        {% for projectinfo in project %}
            <div class="col-sm-6">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ projectinfo.title }}</h5>
                        <p class="card-text">{{ projectinfo.descriptions | safe }}</p>
                    </div>
                </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}

shreebalaji/templates/contactus.html
{% extends 'base.html' %}
{% block content %}
    <style>
        .jumbotron {
            padding-top: 10px;
            padding-bottom: 10px;
            background-color: gray;
        }
    </style>
    <div class="jumbotron">
        <h1 class="display-4" align="center"><b>Contact Us</b></h1>
    </div>
    <div>
        {% if messages %}
            <div class="messages" align="center">
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <div class="alert alert-success" role="alert"><strong>Well
                            done!</strong> {{ message }}</div>
                    {% endif %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-warning" role="alert"><strong>Sorry!</strong> {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-header bg-primary text-white"><i class="fa fa-envelope"></i> Contact us.
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url 'shreebalaji:contactus' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" name="name" aria-describedby="emailHelp"
                                           placeholder="Enter name" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email address</label>
                                    <input type="email" class="form-control" name="email" aria-describedby="emailHelp"
                                           placeholder="Enter email" required>
                                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with
                                        anyone else.</small>
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <textarea class="form-control" name="message" rows="6" required></textarea>
                                </div>
                                <div class="mx-auto">
                                    <button type="submit" class="btn btn-primary text-right" name="submit">Submit
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-4">
                    <div class="card bg-light mb-3">
                        <div class="card-header bg-success text-white text-uppercase"><i class="fa fa-home"></i>
                            Marketing Office
                        </div>
                        <div class="card-body">
                            <i class="fas fa-home mr-3"></i> Head office- New Baneswor, Kathmandu, Nepal</p>
                            <i class="fas fa-envelope mr-3"></i> tmbalasingh@gmail.com</p>
                            <i class="fas fa-envelope mr-3"></i> shree.bhe@gmail.com</p>
                            <i class="fas fa-phone mr-3"></i> +977 14483582
                        </div>
                    </div>

                    <div class="card bg-light mb-3">
                        <div class="card-header bg-success text-white text-uppercase"><i class="fa fa-home"></i> Factory
                            Address
                        </div>
                        <div class="card-body">
                            <i class="fas fa-home mr-3"></i> Jhool Pokhari, Kathmandu, Nepal</p>
                            <i class="fas fa-envelope mr-3"></i> tmbalasingh@gmail.com</p>
                            <i class="fas fa-envelope mr-3"></i> shree.bhe@gmail.com</p>
                            <i class="fas fa-phone mr-3"></i> +977-9801070664

                        </div>
                    </div>

                </div>
            </div>
        </div>
{% endblock %}

shreebalaji/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block content %}
    <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel" align="center"
         style="padding-bottom: 20px">
        <div class="carousel-inner">
            <div class="carousel-item active" data-interval="1000">
                <img src="{% static 'images/firstslide.jpg' %}" class="d-block w-100" alt="..." height="400"
                     style="width: 300px">
            </div>
            {% for banner in banners %}
                <div class="carousel-item" data-interval="1000">
                    {% thumbnail banner.image "1300x400" crop="center" as im %}
                        <img src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="card w-100">
     <div class="card-header text-center">
            <h2> About Company</h2>
        </div>
        <div class="card-body">
            <div align="center" style="padding-bottom: 5px">
                  <img src="{% static 'images/logo.png' %}" alt="logo"height="100px" width="120px">
            </div>
            <p class="card-text" align="justify">
            <b>ShreeBalaji Hydro and Engineering Pvt. Ltd</b> was established in the year 2075 under Companies Act 2006 with
            <b>registration number 189101/74/075 and VAT number 606714822</b>. Established under Private Firm Registered Act
            2014, our company was first registered with the name Shree Balaji Engineering works which was a proprietor
            company with its registration number 40983/1683 and VAT number as 601057621.<br/><br/> The head office of the company
            is located at <b>New Baneshwor, Kathmandu, Nepal</b> . In short this works in the field of Erection of Hydro
            mechanical and Structural Engineering Services since 2013. Our key motive is creating an outstanding
            experience for each and every one of our clients.<br/><br/>

            We provide excellent commitment in field of <b>planning, design, fabrication, installation, quality management
            and testing & commissioning</b>. Our experienced, knowledgeable team can perform detail engineering, fabrication
            and installation of all the hydro-mechanical items and structures such as Headrace and Penstock pipes, Bell
            mouths, Gates and Stop logs, Hoisting, Bends, Trash racks, Bifurcations, Flushing Pipes, Draft Tubes,
            Expansion Joints, etc. We ensure you timely project completion, end-to-end quality management and budget
            control.
            </p>
            <a href="{% url 'shreebalaji:aboutus' %}" class="btn btn-primary">Explore More</a>
        </div>
    </div>
    <div class="card text">
        <div class="card-header text-center">
            <h2>Objectives of Company </h2>
        </div>
        <div class="card-body">
            <p class="card-text-left">
            <ul>
                <li>To work in field of Hydro & Electromechanical equipment.
                </li>
                <li>Perform fabrication related work of Roof Trusses, Suspension Bridges, Truss bridge, Vertical and
                    Underground Storage tanks, Penstock pipes, Gates etc.
                </li>
                <li>To provide service based task or perform task of heavy equipments</li>
                <li>To train the local manpower to carry out the Hydro mechanical works.
                </li>
            </ul>
            </p>
        </div>
    </div>
    <div style="padding-bottom: 10px"></div>
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">OnGoing Projects</h3>
                    <h6 class="card-subtitle mb-2 text-muted">1. Gelung Khola Hydro Electric Project (3.2 MW),
                        Sindhupalchowk</h6>
                    <p class="card-text">
                    <ul>
                        <li>Client: Gelung Khola Hydropower Company Ltd.</li>
                        <li>Scope of Work: Installation of penstock pipes, headrace pipes, bends, saddle plates, wear
                            plates, reducers.
                        </li>
                    </ul>
                    </p>
                </div>
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">2. Arun Kaveli Hydro Electric Project (25 MW), Ilam</h6>
                    <p class="card-text">
                    <ul>
                        <li>Client: Api Hydromechinal Pvt. Ltd.</li>
                        <li>Scope of Work: Overall Monorail Hoisting Structures.</li>
                    </ul>
                    </p>
                    <a href="{% url 'shreebalaji:ongoing' %}" class="btn btn-primary">Explore More</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Completed Projects</h3>
                    <h6 class="card-subtitle mb-2 text-muted">1. Upper Mai Hydropower Project (9.98 MW)</h6>
                    <p class="card-text">
                    <ul>
                        <li>Client: Mai Valley Hydro Power Company</li>
                        <li>Scope of Work: Fabrication and Installation of Radial Gate at Undersluice, Intake Gate,
                            Flushing Gate, Inlet & Outlet Gate, Sediment Flushing Gate at Settling Basin, overflow
                            Stoplog, Stoplog at Undersluice, Fine Trash Rack at Settling Basin & Forebay Outlet & many
                            more.
                        </li>
                    </ul>
                    </p>
                </div>
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">2. Mai khola HPP (22MW)</h6>
                    <p class="card-text">
                    <ul>
                        <li>Client: Sanima Hydropower Pvt. Ltd</li>
                        <li>Scope of work: Fabrication and Installation of Intake Stoplog, Undersluice Stoplog, Draft
                            Tube, Intake overflow.
                        </li>
                    </ul>
                    </p>
                    <a href="{% url 'shreebalaji:completed' %}" class="btn btn-primary">Explore More</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}